# Generated by Django 2.1.5 on 2019-02-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply',
            field=models.TextField(default='Reply', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('url',)},
        ),
    ]
