# Generated by Django 2.1.5 on 2019-02-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190211_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='published_time',
            new_name='Q_published_time',
        ),
        migrations.RenameField(
            model_name='ask',
            old_name='text',
            new_name='Q_text',
        ),
        migrations.RenameField(
            model_name='ask',
            old_name='title',
            new_name='Q_title',
        ),
        migrations.RemoveField(
            model_name='ask',
            name='url',
        ),
    ]
