# Generated by Django 2.1.5 on 2019-02-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190211_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='Q_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
