# Generated by Django 2.1.5 on 2019-02-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190212_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published_time']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_time']},
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
