# Generated by Django 2.1.5 on 2019-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
