# Generated by Django 2.1.5 on 2019-02-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
