# Generated by Django 2.1.5 on 2019-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20190213_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
