# Generated by Django 2.1.5 on 2019-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20190213_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('J_title', models.CharField(max_length=100)),
                ('J_url', models.CharField(max_length=100)),
                ('published_time', models.DateTimeField()),
            ],
        ),
    ]
