# Generated by Django 2.1.5 on 2019-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
