# Generated by Django 2.1.5 on 2019-02-25 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20190214_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-published_time']},
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='date_changed',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='key',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='score',
        ),
    ]
